version: 2
updates:

  - package-ecosystem: npm
    directory: "/"
    versioning-strategy: increase-if-necessary
    schedule:
      interval: monthly
    labels:
      - dependencies
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    labels:
      - dependencies
